[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.gd']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'vendor/bin/heroku-php-apache2'

[variables]
PHP_VERSION = '8.2'
COMPOSER_ALLOW_SUPERUSER = '1'
APP_ENV = 'production'
APP_DEBUG = 'false'